### PR TITLE
Integrate CST: Work in progress

### PR DESCRIPTION
**Pull request by mdevils**
Sorry for a huge **Work In Progress** pull request, just want to keep you informed about the current integration I'm working on.

In this pull request:
* Use `CST` instead of `AST with token hacks` (https://github.com/mdevils/cst)
* Simplify `JsFile` and rules.
* Improve assertions in tests using `chai` and `chai` extensions (it is very hard to make huge changes with the current error messages).

Feel free to discuss changes. Any help is very appreciated.

/cc @markelog @hzoo @mrjoelkemp @mikesherov @zxqfox

### CODE REVIEW

**Comment by markelog** [comment]
Jesus, looks intimidating :-)

**Comment by mdevils** [comment]
I wish I could split changes somehow :)

**Comment by mikesherov** [comment]
@mdevils would be great if you could join the CST discussion happening in estree/estree#41 because a lot of this work will be moving directly into the Esprima and Acorn parsers themselves. Looks good to have a reference implementation to point to though!

**Comment by markelog** [comment]
Since this pull affects a lot (or we could say everything), it should be landed in master asap, since it would be really, really hard to merge it with master in the near future

**Comment by mrjoelkemp** [comment]
Setting time aside to review today or tomorrow. Lots to take in here.

**Comment by mikesherov** [comment]
I don't think this should be merged into master without at least having a discussion with the estree folks.

**Comment by markelog** [comment]
> I don't think this should be merged into master without at least having a discussion with the estree folks.

Working implementation might be good place to start iteratively improving CST image, there is room and need for discussion

**Comment by markelog** [comment]
Okay, merged 2.0 to master, see ya in pull with different target

**Comment by mdevils** [comment]
@mikesherov added a comment in CST thread of estree

**Pull request closed without merging**
