### PR TITLE
Preset: update Wordpress preset

### LINKED ISSUE #1188: WordPress preset: flag yoda conditions only for equality comparison
I noticed that JSCS is flagging "Yoda conditions" for non-equality operators (<, >, <=, >=).

After #1026 is merged, alter the WordPress preset so yoda conditions are only required for "==", "===", "!=" and "!==".

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9969592-wordpress-preset-flag-yoda-conditions-only-for-equality-comparison?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Slayer95**
Only disallow Yoda conditions for equality operators.

Closes #1452
Fixes #1188

### CODE REVIEW

**Comment by hzoo** [comment]
:+1: although it looks like it was merged in 2.0 branch

**Comment by Slayer95** [comment]
That's because it requires Yoda's support for an array of operators, which is only merged in 2.0.

**Comment by hzoo** [comment]
So we can close (since `Closes only works when merging into master right)

**Comment by markelog** [comment]
@hzoo when we merge 2.0 to master they all will close

**Comment by hzoo** [comment]
haha good point.

**Pull request closed without merging**
