### PR TITLE
Implemented method exception for disallowSpaceAfterObjectKeys, fixes …

### PR DESCRIPTION
**Pull request by alawatthe**
…#1582, #1788

### CODE REVIEW

**Comment by markelog** [comment]
LGTM

**Comment by hzoo** [comment]
Nice! Didn't seem too bad haha

**Comment by alawatthe** [comment]
You're right, it really wasn't too difficult :-D and since it was breaking our build I thought I fix it quickly.

For tasks like this, I really find [Felix Kling's JS AST Explorer](http://felix-kling.de/esprima_ast_explorer/) very helpful.

**Comment by hzoo** [comment]
Yep I'm been using it a lot as well (and some contributions). Also you can use astexplorer.net as the link now.

**Pull request closed without merging**
