### PR TITLE
JsFile::getFirstTokenOnLine implementation (for indentation rules)

### PR DESCRIPTION
**Pull request by mdevils**
I've implemented `getFirstLineToken` to improve indentation rules.

@mikesherov, please take a look.

### CODE REVIEW

**Comment by mikesherov** [comment]
Looks good except can we name it `getFirstTokenOnLine`? Makes the purpose clearer in English.

**Comment by mdevils** [comment]
Renamed it :wink:

**Comment by mikesherov** [comment]
:+1:

**Comment by zxqfox** [comment]
Ouch, nice! :+1:

**Pull request merged**
