### PR TITLE
use this.getOptionName() for consistency, options variable name

### PR DESCRIPTION
**Pull request by hzoo**

### CODE REVIEW

**Comment by markelog** [comment]
That is a lot of thoughtful work, wow. Although, i fear we would have to do it all over again, after we address https://github.com/jscs-dev/node-jscs/issues/895.

Will merge this in couple hours.

**Comment by mrjoelkemp** [comment]
LGTM nice work @hzoo!

**Comment by hzoo** [comment]
I saw we had a few errors in docs since we were typing the rule names over and over and sometimes spelling it wrong. Sometimes its because we just copy/paste from another rule and end up with the wrong name. 

Would be interesting if we could get the option name from the file name but maybe that would be weird?

Yeah I think a declarative config would be great.

**Comment by mrjoelkemp** [comment]
@hzoo The file name idea is a good one, but doesn't work for the browser bundle.

**Comment by markelog** [comment]
Merged, as always, thank you :-); btw, don't bother put "Closes" in the commit body, seems tedious to force-push into PR to put correct pull number. We can always do it for ya.

**Comment by hzoo** [comment]
Yeah it is kind of tedious - sometimes I actually do it before I push since I know the next issue number (by assuming no one else is doing a PR/issue at the time I push)

**Pull request closed without merging**
