### PR TITLE
Fix: Sparse arrays in rules with spacing and commas

### LINKED ISSUE #1909: Bug: Sparse arrays in any rules with spacing and commas
Example: `["foo", , “bar”]`

I know there's an issue for
- [x] `disallowSpaceBeforeComma`
- [x] `disallowSpaceBeforeBinaryOperators`
- [x] `disallowSpaceAfterComma`
- [x] `disallowSpaceAfterBinaryOperators`

// not an issue
- [x] `requireSpaceBeforeComma`
- [x] `requireSpaceAfterComma`

maybe
- [ ] `disallowCommaBeforeLineBreak`
- [ ] `requireCommaBeforeLineBreak`

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27610628-bug-sparse-arrays-in-any-rules-with-spacing-and-commas?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by bjdixon**
Added tests against sparse arrays and fixes where needed.

Fixes #1909

### CODE REVIEW

**Comment by bjdixon** [comment]
As I was touching the files anyway I took the opportunity to add extra tests for ` disallowSpaceBeforeComma `, `requireSpaceBeforeComma `, ` disallowSpaceAfterComma ` and ` requireSpaceAfterComma ` in keeping with a previous @hzoo [comment](/jscs-dev/node-jscs/pull/1822#issuecomment-144499392)

**Comment by markelog** [comment]
More tests are awesome, but it usually better to do it in different commits, like if we notice some bugs with this pr, we would need to revert the whole thing since it all done in one commit, including unrelated changes it is also better to differentiate since it might be hard to next guy understand what and why was done here with `git blame` or analogues commands or gui

**Comment by markelog** [comment]
What about `(require | disallow)CommaBeforeLineBreak` rules?

**Comment by markelog** [comment]
Okay, landing pr, but not closing the ticket, because of omission of `(require | disallow)CommaBeforeLineBreak` rules.

**Pull request closed without merging**
