### PR TITLE
disallowAnonymousFunctions: Added explanations about the rule.

### LINKED ISSUE #1884: Add in the website's documentation of a rule, the rational for said rule
Especially for new comers in a team, it may be easier to embrace/accept a coding style rule if you know what kind of mistakes this rule protect you against

for example http://jscs.info/rule/disallowAnonymousFunctions ,  what kind of bug/problem may emerge if I use anonymous function ?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27500711-add-in-the-website-s-documentation-of-a-rule-the-rational-for-said-rule?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Nargonath**
Added information on the reason behind using this rule.

Fixes #1884

### CODE REVIEW

**Comment by markelog** [comment]
Nice one, thank you

**Comment by Nargonath** [comment]
I'm the one who should thank you. That's really nice of you guys to do the "beginner-friendly" label. First time contributing to OpenSource project.

**Comment by hzoo** [comment]
Awesome job @Nargonath! Hope to see you more around here!

**Comment by Nargonath** [comment]
@hzoo Thank you. I'll stick around for sure.

**Pull request closed without merging**
