### PR TITLE
Configuration: exclude `node_modules/` by default

### LINKED ISSUE #1461: excludeFiles: add "node_modules/**" by default
So people don't need to add `node_modules/**` every time (or forget and freeze their cli).

Similar argument could be made for `bower_components` (@zxqfox)

Should be able to include again by using `!node_modules` already I think?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/22345338-excludefiles-add-node_modules-by-default?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lpil**
Closes #1461

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Lgtm

**Comment by mrjoelkemp** [comment]
Maybe add a comment in the docs?

**Comment by hzoo** [comment]
looks good!

**Comment by mrjoelkemp** [comment]
Thanks again for contributing @lpil!

**Comment by lpil** [comment]
:dancer: Always happy to help with linters ;D

**Pull request closed without merging**
