### PR TITLE
Preset: change value of "requireDotNotation" rule for jquery preset

### PR DESCRIPTION
**Pull request by markelog**

### CODE REVIEW

**Comment by mikesherov** [comment]
Where does this come from? I don't doubt the validity, just curios.

**Comment by markelog** [comment]
> Where does this come from?

Just a thought, same use-case as with https://github.com/jscs-dev/node-jscs/issues/866

**Comment by mikesherov** [comment]
@markelog LGTM

**Comment by mikesherov** [comment]
Landing.

**Pull request closed without merging**
