### PR TITLE
disallowSpaceBeforeSemicolon: add `allExcept` option

### LINKED ISSUE #1640: disallowSpaceBeforeSemicolon is incompatible with requiring spaces inside for()
```
  1730 |    nodeData = nodesData[ nodeIndex ];
  1731 |
Illegal space before semicolon at core/editable.js :
  1927 |   var insideOfList = path.contains( DTD.$list );
  1928 |
  1929 |   for ( ; nodeIndex < nodesCount; ++nodeIndex ) {
----------------^
```

I use:

```
"disallowSpaceBeforeSemicolon": true
"requireSpacesInsideParentheses": "all",
```

Full config – https://github.com/ckeditor/ckeditor-dev/blob/master/dev/tasks/jscs-config.json (without `disallowSpaceBeforeSemicolon`).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25479250-disallowspacebeforesemicolon-is-incompatible-with-requiring-spaces-inside-for?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by markelog**
Also, do not trigger error if it's first token

/cc @ShashankaNataraj

Fixes #1640

### CODE REVIEW

**Comment by ShashankaNataraj** [comment]
@markelog Looks good, but wouldve loved to work on this issue but its completed by you I see :)

**Comment by markelog** [comment]
Oh, sorry, was asking about it in original ticket, i guess i should have ask you directly :/

**Comment by ShashankaNataraj** [comment]
@markelog No problemo, if in future any issues crop up with my previous PR's, kindly cc me on them. Id love to contribute to node-jscs :)

**Comment by markelog** [comment]
Cool, will do

**Pull request closed without merging**
