### PR TITLE
requirePaddingNewLineAfterVariableDeclaration: fix ES6 false positives

### PR DESCRIPTION
**Pull request by MartinKolarik**

### CODE REVIEW

**Comment by zxqfox** [comment]
Looks :+1:

**Comment by hzoo** [comment]
Looks good - similar to #1191. Thought I didn't see any others but maybe we should look for `=== 'var'`.

**Comment by mikesherov** [comment]
:+1:

**Comment by markelog** [comment]
Closing it in favour of  #1191, nevertheless, thank you @MartinKolarik.

**Comment by hzoo** [comment]
Oh @markelog I think we need to add this one since it's the same fix applied to another rule. #1191 was for `requireLineBreakAfterVariableAssignment` and this seems to be the same issue for `requirePaddingNewLineAfterVariableDeclaration`?

Looks like the only other rule it would apply to is `requireMultipleVarDecl`.

**Comment by markelog** [comment]
Oh, shoot #1191 and this one are two different fixes :-), reopening

**Comment by yaycmyk** [comment]
You should also add a test for mixed types.

const, then let for example

**Comment by markelog** [comment]
@yannickcr it's done in https://github.com/jscs-dev/node-jscs/pull/1245/files, thanks for keeping an eye on it.

**Comment by markelog** [comment]
Thank you

**Pull request closed without merging**
