### PR TITLE
Skipped tests2

### PR DESCRIPTION
**Pull request by hzoo**

### CODE REVIEW

**Comment by markelog** [comment]
Judging by the travis log, it seems we need to increase the test timeout?

**Comment by hzoo** [comment]
Yeah only for those tests I guess

**Comment by hzoo** [comment]
Oh, I see - that sucks - so that timeout was for my computer

**Comment by markelog** [comment]
> Means that the tests were taking < 3 sec and now > 15 which is pretty bad and something we certainly need to investigate?

Definitely! /cc @mdevils

**Pull request closed without merging**
