### PR TITLE
New Rule: disallowNotOperatorsInConditionals

### PR DESCRIPTION
**Pull request by hzoo**
WIP. for #1205 

~~Need to figure out a better name~~, also other cases?

~~Looks like I would need to add a check for `!=` (inequality) and change the naming for `!==` to be `strict inequality operator`~~

### CODE REVIEW

**Comment by SimenB** [comment]
@hzoo Could you cover ternaries as well?

Error
``date = !_.isEmpty(date) ? moment(date, 'DD-MM-YYYY') : null;``

Correct
``date = _.isEmpty(date) ? null : moment(date, 'DD-MM-YYYY');``

**Comment by hzoo** [comment]
Ok with that the rule name/docs should change as well. `disallowNotOperatorsInConditionals` to cover both?

**Comment by SimenB** [comment]
Yeah, sounds good :+1:

**Comment by zxqfox** [comment]
Totally agreed about conditionals.

But are you sure about plural in naming?
`disallowNotOperatorsInConditionals` vs `disallowNotOperatorInConditional`

**Comment by hzoo** [comment]
As of now, we will be checking for `!==, !=, !a`
in `if()` and ternary `(a ? b : c)`

**Comment by markelog** [comment]
Still a WIP?

**Comment by hzoo** [comment]
Yeah I just have to change the rule name to `disallowNotOperatorsInConditionals` and add a check for ternary statement and `!=` which I can do soon.

**Comment by hzoo** [comment]
Updated the rule name to `disallowNotOperatorsInConditionals`, fixed examples/tests - added check for `!=` and ternaries.

**Comment by markelog** [comment]
I would ask for opposite rule, but really, who would need that?

**Comment by zxqfox** [comment]
`validate*`?

**Comment by markelog** [comment]
Yeah, was thinking the same thing, but `validateNotOperatorsInConditionals` sounds peculiar to me.

Ideas?

**Comment by zxqfox** [comment]
`validateTestInConditionals`?

**Comment by markelog** [comment]
@hzoo ?

**Comment by SimenB** [comment]
validateNegationInConditionals? validateNoNegationInConditionals?

**Comment by mikesherov** [comment]
We have disallow/require rules without opposites. No need to force it to be named "validate".

**Comment by markelog** [comment]
I think it would be a good naming convention, we can start enforcing it now and continue to use it in new major version

**Comment by hzoo** [comment]
I still like `disallowNotOperatorsInConditionals`

**Comment by markelog** [comment]
Me too, but see above, i'd like establish convention for these kind of rules.

**Comment by zxqfox** [comment]
@markelog What you think about leaving it as is for now and try to rethink it in the way to 2.0? I still want to revive your issue with new shiny configurations.

**Comment by markelog** [comment]
Works for me, will land this soon

**Comment by hzoo** [comment]
Oh I didn't add it to the commit - #1205.

**Pull request closed without merging**
