### PR TITLE
disallowParenthesesAroundArrowParam: make exception when using a defa…

### LINKED ISSUE #1411: disallowParenthesesAroundArrowParams: make exception for default parameter
Dang found an issue already (should of ran these on a larger codebase).

```js
var a = {
  a: (b = 1) => { return 'hi'; }
};
```
We can't remove the parens when using default params.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/18742109-disallowparenthesesaroundarrowparams-make-exception-for-default-parameter?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by hzoo**
…ult parameter

Fixes #1411.

Had to fix maximumLineLength issue.
Also did two different checks (one is esprima-harmony and other the esprima 2.3/estree)

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Looks good. :+1:

**Comment by zxqfox** [comment]
Agreed, good to me! :+1:

**Comment by markelog** [comment]
@zxqfox @mrjoelkemp hey there, if there is at least to "LGTM" you really should such pr :-)

**Comment by mrjoelkemp** [comment]
Done. Thanks @hzoo

**Pull request closed without merging**
