### PR TITLE
Cleanup: use iterateTokensByTypeAndValue

### PR DESCRIPTION
**Pull request by hzoo**
@mikesherov

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
LGTM but what's the benefit here?

**Comment by hzoo** [comment]
No benefit - just for consistency with https://github.com/jscs-dev/node-jscs/commit/28ba35b23ca70a767f7e03fbb9e56617f74203a4 and https://github.com/jscs-dev/node-jscs/commit/41d250251b7ab75e476b75666bbb1db93bcd4551

**Comment by mikesherov** [comment]
@hzoo have you gone through all rules to make this update? I'd like that if possible please.

**Comment by hzoo** [comment]
I ctrl-f'd for `if (token.value` and this was the only other instance left.

**Comment by hzoo** [comment]
Ok actually found a few more after some searching. I also went ahead to use `this.getOptionName()` as well.

**Comment by hzoo** [comment]
Looks like Travis failed

**Pull request closed without merging**
