### PR TITLE
Update regenerate to ~1.2.1

### PR DESCRIPTION
**Pull request by cvrebert**
Skipped `browserify` since it would be a new major version.

### CODE REVIEW

**Comment by mikesherov** [comment]
@cvrebert I assume you tried rerunning the generate script and than ran the test suite?

**Comment by mikesherov** [comment]
Thanks again for updating this stuff!

**Comment by cvrebert** [comment]
Yep.

**Comment by mikesherov** [comment]
Thanks again @cvrebert

**Pull request closed without merging**
