### PR TITLE
requirePaddingNewlinesAfterBlocks: arrays act like objects for the last item

### PR DESCRIPTION
**Pull request by christophehurpeau**
And added the airbnb check for the section [18.6](https://github.com/airbnb/javascript#18.6)

```js
const arr = [
  function foo() {
  },

  function bar() {
  },
];

return arr;
```

### CODE REVIEW

**Comment by markelog** [comment]
Why? Could you use `inArrayExpressions` option?

**Comment by christophehurpeau** [comment]
`inArrayExpressions` means anywhere in the array.
This require newlines between functions inside the array except the last item, the same behavior than for objects

**Comment by cyrilf** [comment]
:+1: seems consistent with the `objects` rules indeed

**Comment by christophehurpeau** [comment]
up ?

**Comment by markelog** [comment]
Sounds reasonable, could you add the same logic for function call parentheses?

**Comment by christophehurpeau** [comment]
added for call parentheses :)

**Comment by christophehurpeau** [comment]
up ?

**Comment by markelog** [comment]
Thank you

**Pull request closed without merging**
