### PR TITLE
TrailingComma: fixed error location

### LINKED ISSUE #1018: (require|disallow)TrailingComma reports error one line to low
With the code:
```js
var obj = {
    foo: 'foo',
};

var arr = [
    'foo',
];
```
I get the following output (jscs version 1.11.0, ```"disallowTrailingComma": true```):

```
->jscs foo.js 
Extra comma following the final element of an array or object literal at foo.js :
     1 |var obj = {
     2 |    foo: 'foo',
     3 |};
--------^
     4 |
     5 |var arr = [

Extra comma following the final element of an array or object literal at foo.js :
     5 |var arr = [
     6 |    'foo',
     7 |];
--------^
     8 |


2 code style errors found.
```

I would expect to get (note the position of the dashed line):
```
->jscs foo.js 
Extra comma following the final element of an array or object literal at foo.js :
     1 |var obj = {
     2 |    foo: 'foo',
----------------------^
     3 |};
     4 |

Extra comma following the final element of an array or object literal at foo.js :
     4 |
     5 |var arr = [
     6 |    'foo',
-----------------^
     7 |];
     8 |


2 code style errors found.
```

The same problem exists for ```requireTrailingComma```.

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/8394181-require-disallow-trailingcomma-reports-error-one-line-to-low?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by zxqfox**
- also added loc option to [no]TokenBefore

Fixes #1018

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
+1

**Comment by mikesherov** [comment]
What other rules use tokenBefore? If the answer is none, then should use the expectedTokenBefore loc rather than providing an option to specify a location.

**Comment by mikesherov** [comment]
The idea is that the rules shouldnt have to think about where the error is.

**Comment by zxqfox** [comment]
@mikesherov Yup ;-) Done.

**Comment by mikesherov** [comment]
Much better :-)

**Pull request closed without merging**
