### PR TITLE
Small improvements for token-assert module

### PR DESCRIPTION
**Pull request by markelog**
/cc @mdevils

### CODE REVIEW

**Comment by mdevils** [comment]
Hi, Oleg.

Checked out this PR. For me it became less clear.

@mikesherov, can you please check this out?

**Comment by markelog** [comment]
> Checked out this PR. For me it became less clear.

Could you elaborate?

**Comment by markelog** [comment]
Will merge this for now, since i need this for further work on other things, will revert this, if these changes would not be acceptable

**Comment by mrjoelkemp** [comment]
What motivated the property name change? I agree with Murat that `nextToken` was a better name. I'd think what is currently `token` should be `prevToken` and `nextToken/subjectToken` should just be `token` or `currentToken`.

**Comment by markelog** [comment]
This `nextToken/subjectToken` could be very well previous or the next token, so i would choose a name which would be agnostic to the direction, since "direction" doesn't matter, because it doesn't reflected in checks of those methods.  Same with `token` property.

Bikeshedding process is as fun as i remember it.

**Comment by mdevils** [comment]
Errr... why did you merge? For me `nextToken` is way clearer than `subjectToken`.

**Comment by mikesherov** [comment]
@mdevils

> Will merge this for now, since i need this for further work on other things, will revert this, if these changes would not be acceptable

I think Oleg just wanted some solid ground to work off of. 

I do think though that "next" and "previous" imply position in text. @markelog's desire to rename them is good. I am not sure "subjectToken" is a good name either. 

@markelog, you can't start painting a red shed blue and then complain how not fun it is to paint!

**Pull request merged**
