### PR TITLE
Fix: do not extract/lint html by default

### LINKED ISSUE #1828: disallowTabs fails with TypeError, Extracting HTML by default
```
TypeError: Cannot call method 'replace' of undefined
    at renderLine (/home/vagrant/www/node_modules/jscs/lib/errors.js:250:17)
    at Object.Errors.explainError (/home/vagrant/www/node_modules/jscs/lib/errors.js:181:13)
    at /home/vagrant/www/node_modules/jscs/lib/reporters/console.js:16:36
    at Array.forEach (native)
    at /home/vagrant/www/node_modules/jscs/lib/reporters/console.js:14:35
    at Array.forEach (native)
    at Object.module.exports [as writer] (/home/vagrant/www/node_modules/jscs/lib/reporters/console.js:9:22)
    at /home/vagrant/www/node_modules/jscs/lib/cli.js:151:18
    at Array.0 (/home/vagrant/www/node_modules/vow/lib/vow.js:711:56)
    at Object.callFns [as _onImmediate] (/home/vagrant/www/node_modules/vow/lib/vow.js:23:35)
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27081681-disallowtabs-fails-with-typeerror-extracting-html-by-default?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by hzoo**
Fixes #1828
Closes gh-1870

### CODE REVIEW

**Comment by hzoo** [comment]
Would doing this work for now? @lahmatiy

**Comment by lahmatiy** [comment]
Actually it's not fix #1828, since issue is in wrong line position.
But, yeah, we should disable extract by default (make it opt-in). Will try do it later.

**Comment by hzoo** [comment]
Oh ok I guess I'l close this then

**Comment by hzoo** [comment]
Although I'd think it would be better to release a patch since we don't want people getting random linting errors from html files when updating?

**Comment by lahmatiy** [comment]
Agree

**Pull request closed without merging**
