### PR TITLE
New Rule: disallowNodeTypes

### LINKED ISSUE #1389: New Rule: disallowNodeTypes
Ref https://github.com/jscs-dev/node-jscs/issues/1385#issuecomment-102881542.
> Maybe we should have a disallowLabelStatements rule

So instead of a one off rule (`disallowLabelStatements`), we can do the same as `disallowIdentifierNames`, and `disallowKeywords`? Although I don't know what other statements we would want to disallow that is like this (since most would be keywords)

Need a better name - @ljharb?

Would take an array of strings from: https://github.com/jquery/esprima/blob/master/esprima.js#L108-169

`"disallowASTStatements": ["LabelStatement"]`
`"disallowNodeTypes": ["LabelStatement"]`

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/15742538-new-rule-disallownodetypes?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by hzoo**
Fixes #1389 

Need some help here.

Esprima node types: https://github.com/jquery/esprima/blob/758196a1c5dd20c3ead6300283a1112428bc7045/esprima.js#L108-L169

Acorn/babel node types:
https://github.com/babel/babel/blob/65a44a1e131c8bc336b218991bae7548176de283/src/babel/types/alias-keys.json#L2-L121

Espree node types: https://github.com/eslint/espree/blob/a23b65db10648daf7d4b0761b0ce09eea864550a/lib/ast-node-types.js#L41-L115

Do we want to check if the node types given in the array are supported by the parser or just let it error?

### CODE REVIEW

**Comment by ljharb** [comment]
\( ﾟ◡ﾟ)/ 👍

**Comment by mrjoelkemp** [comment]
This feels like a JSHint rule.

**Comment by hzoo** [comment]
Yeah that's true. However, we do have disallowIdentifiers, and disallowKeywords that are used with the intent to disallow parts as well (`with`, certain methods like `eval` or something) so this rule is created with a similar purpose?

**Comment by mrjoelkemp** [comment]
Sure then. DisallowKeywords was likely discussed at length and accepted so
this is fine by me.

**Comment by markelog** [comment]
mm, where broad rule, couldn't hurt though

**Comment by hzoo** [comment]
@markelog was from https://github.com/jscs-dev/node-jscs/issues/1385#issuecomment-102881542 - originally to disallow `LabeledStatements`

**Comment by markelog** [comment]
Yeah, i read it, there might be use-cases for that, sure, it feels as advanced rule though

**Comment by hzoo** [comment]
Yeah that's definitely true, since you have to know what node types are/esprima/ASTs.

**Pull request closed without merging**
