### PR TITLE
Change 'Value' to 'Values' to be consistent

### PR DESCRIPTION
**Pull request by MunGell**
Not as important, so moved these changes into separate PR. Just to be consistent – seems like most of the rules have "Values" instead of "Value".

### CODE REVIEW

**Comment by TheSavior** [comment]
It seems like It should be `value` if there is only one choice, and `values` if there is more.

**Comment by mrjoelkemp** [comment]
Agreed with @TheSavior here. Would you mind making that change where appropriate @MunGell? That would be a great win for the docs.

**Comment by TheSavior** [comment]
And as a side note, is this something that we could automate ourselves for the future? Anything that can be enforced by linters or tests is better than manual checking and enforcing down the line.

**Comment by mrjoelkemp** [comment]
Seems like it would depend on #480.

**Comment by TheSavior** [comment]
Not necessarily. I could see us trying to generate those doc blocks automatically, but I could also imagine us trying to figure out what a custom jscs rule (or another system if there was a better way) to validate the contents of docblocks.

**Comment by MunGell** [comment]
I was thinking about changing it to singular form where necessary, but it is looking like we are using just one form in all the rules. I can change it, should I do the same for "Type"/"Types"?

**Comment by mrjoelkemp** [comment]
Yes please. The docs should be grammatically correct.

**Comment by MunGell** [comment]
Hey guys,

This should be corrected now, please take a look at the diff.

**Comment by mrjoelkemp** [comment]
@MunGell Great work here! Thanks for contributing. Landed!

**Comment by MunGell** [comment]
You are welcome!

**Pull request closed without merging**
