### PR TITLE
Preset: node-style-guide

### LINKED ISSUE #1071: Add node-style-guide preset
https://github.com/felixge/node-style-guide

Related #1070 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8623050-add-node-style-guide-preset?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by hzoo**
Fixes #1071 

Initial preset config.

Not sure if the preset should only include rules based on the explicit statements or also include rules based on the code in the examples that is implied.

An example is function spacing.

```js
function BankAccount() {
}
setTimeout(function() {
  client.connect(afterConnect);
}, 1000);
```
the rules could be inferred to be 
```js
"disallowSpacesInFunction": {
    "beforeOpeningRoundBrace": true
},
"requireSpacesInFunction": {
    "beforeOpeningCurlyBrace": true
},
```

I can move that huge table of possible rules here as well?

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
> Not sure if the preset should only include rules based on the explicit statements or also include rules based on the code in the examples that is implied.

Also add rules implied from sample.

LGTM

**Comment by hzoo** [comment]
Ok I added some the implied ones like function spacing but there's probably a few rules I didn't see to add based on the style.
We can also think about adding some of the new rules at a later point.

**Comment by markelog** [comment]
@felixge would you mind checking this out?

**Comment by mrjoelkemp** [comment]
Safe to land after rebasing?

**Comment by hzoo** [comment]
rebased - I didn't add anything

**Comment by hzoo** [comment]
Ok I realized I didn't add to the overview or add a line to run the test for the preset. We should update `CONTRIBUTING.md` https://github.com/jscs-dev/node-jscs/blob/master/CONTRIBUTING.md#proposing-additional-presets on that stuff. Can do another commit/PR later if no one else will take i

**Comment by mrjoelkemp** [comment]
Good work @hzoo!

**Pull request closed without merging**
