### PR TITLE
Adding some more fix tests

### PR DESCRIPTION
**Pull request by TheSavior**
Adding whitespace tests to a few rules in #1127

### CODE REVIEW

**Comment by mikesherov** [comment]
@TheSavior great work! Thanks again, as always, for contributing! Perhaps we should make a set of test utility functions, so tests can just say something like:

```
assert.fixesString(input, output);
```
?

**Comment by mdevils** [comment]
Great job!

**Comment by TheSavior** [comment]
@mikesherov I totally agree. Once I got these tests written there is a definite pattern. 

Some tests have an assert that the number of errors is 3 while most verify only 1. It seems like other than an integration test, tests should only ever be asserting one error. Does that seem like a reasonable general rule? Are there obvious cases I'm not thinking of?

**Comment by mikesherov** [comment]
We can solve that with a 3rd param that is the expected number of errors, defaulted to one.

**Comment by mrjoelkemp** [comment]
Good stuff @TheSavior

**Pull request closed without merging**
