### PR TITLE
requireSpaceBeforeBlockStatements: Add number of spaces argument

### LINKED ISSUE #936: Allow requireSpaceBeforeBlockStatements to say "at least 1 space"
v0.11.0 changed `requireSpaceBeforeBlockStatements` to throw an error if you have more than one space before the opening brace. Before 0.11, it would only throw if you had zero spaces.

Could you add a rule for requiring *at least* one space, instead of enforcing *exactly* one?

(Essentially, I'd like some way of opting in to what the rule used to do.)

My use-case: I'm using multiple spaces to line up function bodies.

```js
changeName(studentId, ...args)          { this._change(studentId, 'changeName',          ...args) },
changeCreditsNeeded(studentId, ...args) { this._change(studentId, 'changeCreditsNeeded', ...args) }
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7885177-allow-requirespacebeforeblockstatements-to-say-at-least-1-space?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by olegpesok**
Functionality does not change with a boolean flag, but if an integer is
specified then the integer is the MINIMUM number of spaces required before
a block statement.

Fixes #936

### CODE REVIEW

**Comment by mikesherov** [comment]
@olegpesok thanks for contributing! Rather than adding a `relaxed` parameter, we should get rid of the `spaces` parameter, and instead add an `exactly`, `atLeast`, and `atMost` field like `linesBetween` has to achieve parity. Once we have that, I can review this PR further.

/cc @markelog or @mdevils  or @zxqfox for opinions

**Comment by mdevils** [comment]
@mikesherov  +1

**Comment by mikesherov** [comment]
Can you please rebase this PR and make use of the new options for spacesBetween rather than including a `relaxed` option?

**Comment by markelog** [comment]
Rebased and merged, thank you

**Pull request closed without merging**
