### PR TITLE
Misc: increase mocha timeout

### PR DESCRIPTION
**Pull request by hzoo**
Not sure how much

Pretty annoying when docs changes cause failures https://travis-ci.org/jscs-dev/node-jscs/builds/85757477

### CODE REVIEW

**Comment by hzoo** [comment]
The irony is that the PR failed so that means 3500 isn't enough

**Comment by mrjoelkemp** [comment]
Do we know what's actually taking a long time during these tests? Otherwise, double it and call it a day?

**Comment by hzoo** [comment]
Something with autofixing is taking a long time

**Comment by hzoo** [comment]
Ok I didn't know about https://mochajs.org/#suite-level - we should add that for autofixing tests if we can

**Pull request closed without merging**
