### PR TITLE
Appveyor: freeze stable node version

### LINKED ISSUE #1136: Appveyor: fixup tests and check work on win
Ref https://github.com/jscs-dev/node-jscs/pull/1126#issuecomment-77069354
Ref iojs/io.js#1068

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9174086-appveyor-fixup-tests-and-check-work-on-win?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by zxqfox**
Fixes #1136

### CODE REVIEW

**Comment by zxqfox** [comment]
@mrjoelkemp Seems like all is fine with 0.10/0.12.

Should we test both stables or just 0.12?

cc @mikesherov @markelog @mdevils

**Comment by mrjoelkemp** [comment]
Testing the two versions separately would be nice for isolating v0.12 bugs, if any.

**Comment by zxqfox** [comment]
@mrjoelkemp Yes, but we already testing them in travis. And since appveyor tests much slower we can skip them.

Anyway if bug exists I should go a look into it and check manually both versions. As addition: there are no much windows specific bugs so I think we can left just the latest.

**Comment by mikesherov** [comment]
I like this as is :+1:

**Comment by mrjoelkemp** [comment]
:+1:

**Comment by zxqfox** [comment]
Thanks!

**Pull request closed without merging**
