### PR TITLE
CLI: set "maxErrors" to Infinity with enabled "fix" option

### PR DESCRIPTION
**Pull request by markelog**

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
lgtm minus the test fail

**Comment by markelog** [comment]
Weird, some prs failed, but now, without changing single thing they passing, hm

**Comment by mrjoelkemp** [comment]
babel-jscs worked around some breaking changes in babel that were causing
the failures. The fixes were released in patch versions which travis picked
up fine.

**Comment by sindresorhus** [comment]
Shouldn't this be in the API and not just the CLI? So every consumer don't have to reimplement it. Re: https://github.com/jscs-dev/gulp-jscs/pull/93#issuecomment-144929578

**Comment by markelog** [comment]
Probably, yeah, at this weekend i was planning to refactor `grunt-jscs` module, to have hands on experience on how we should do it

**Pull request closed without merging**
