### PR TITLE
cleanup: remove lib/token-helper

### PR DESCRIPTION
**Pull request by mikesherov**

### CODE REVIEW

**Comment by mikesherov** [comment]
/cc @mdevils @markelog @mrjoelkemp Everything in token-helper is superceded by the simpler methods in `js-file`. It has never been part of a documented public API, and only plugin developers who were specifically scrounging around and looking for it would be effected.

Can we remove this for 1.11 or must we wait for 2.0?

**Comment by mikesherov** [comment]
Whatever we decide, we should document it in our versioning guide, and we should also document the api of JsFile, etc.

**Comment by markelog** [comment]
> 98.03%

Wow!

> Can we remove this for 1.11 or must we wait for 2.0?

Wasn't documented, i think it's safe to remove in minor. 
Perhaps we should start documenting `js-file` and `cli-config` modules, one of the steps would be to solve https://github.com/jscs-dev/node-jscs/issues/747

**Comment by mikesherov** [comment]
Ok. I'm going to land this then and agree we should start thinking how to solve. #747

**Pull request closed without merging**
