### PR TITLE
Preset: allow URLs inside comments in airbnb.json

### PR DESCRIPTION
**Pull request by andreyvolokitin**
Make an exception for URLs inside comments in maximumLineLength rule

### CODE REVIEW

**Comment by markelog** [comment]
Don't see this in their code style, sorry

**Comment by andreyvolokitin** [comment]
They have it in their ESLint config, see https://github.com/airbnb/javascript/issues/819

**Comment by markelog** [comment]
Fair enough

**Comment by markelog** [comment]
Landed! And thank you for the persistence.

**Pull request closed without merging**
