### PR TITLE
New Rule: disableSpacesInGenerator

### LINKED ISSUE #1879: New Rule: (require|disallow)GeneratorSpacing
Ref https://github.com/jscs-dev/node-jscs/issues/1175

```js
function * ()
function* ()
function *()
function*()
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27486409-new-rule-require-disallow-generatorspacing?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1945: There should be an opposite rule to requireSpacesInGenerator
So yeah, there should be `disallowSpacesInGenerator`.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27827081-there-should-be-an-opposite-rule-to-requirespacesingenerator?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Francisc**
Fixes #1879
Fixes #1945

### CODE REVIEW

**Comment by markelog** [comment]
>  Coverage decreased (-0.05%) 

?

**Comment by Francisc** [comment]
Not sure why, it's got double the tests of `requireSpacesInGenerator`.

**Comment by markelog** [comment]
You can check it out by running 

```bash
npm run coverage-html && open coverage.html
``

**Comment by Francisc** [comment]
That throws an ugly error on my machine.
My guess is that is caused by the fact that `configuration.js` got a new line to include the new rule and the spec for it is unchanged.

**Comment by markelog** [comment]
> That throws an ugly error on my machine.

Could you post the output?

**Comment by Francisc** [comment]
Sure:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/.bin/mocha ENOENT
    at exports._errnoException (util.js:860:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
```

**Comment by Francisc** [comment]
Still, isn't it normal to get a lower coverage since `configuration.js` got a new line of text?

**Comment by markelog** [comment]
> Sure:

Does this happen for you on clear master? What OS do you running this on?

> Still, isn't it normal to get a lower coverage since configuration.js got a new line of text?

I don't see coverage drop for `configuration` module, there however only 80% for the `disallow-spaces-in-generator.js` - https://coveralls.io/builds/4163102/source?filename=lib%2Frules%2Fdisallow-spaces-in-generator.js

**Comment by Francisc** [comment]
1. It does happen on master. I'm on Windows 8.1 running Node 5.0.
It's probably a dependency of unit-coverage that fails on Windows.

2. I don't understand why that is, the `disallowSpacesInGenerator` is almost identical to `requireSpacesInGenerator` and has double the tests since I check each of the 2 params set to `true` separately.

**Comment by markelog** [comment]
@mdevils seems as an issue with `unit-coverage`, could you check it out?

**Comment by mdevils** [comment]
Hello @Francisc. I will soon look into this issue and respond.

**Comment by markelog** [comment]
> I don't understand why that is, the disallowSpacesInGenerator is almost identical to requireSpacesInGenerator and has double the tests since I check each of the 2 params set to true separately.

Oh, yeah, that is because require rule covered even more poorly on 69%  :/
/cc @hzoo

**Comment by markelog** [comment]
Okay, so i added supported commit in which i removed some unused logic, increased coverage to 100%, fixed one bug, changed logic a bit.

Those issues are still present in the opposite rule though.

**Comment by Francisc** [comment]
Hi @mdevils. Thank you.

@markelog What's next for this PR?

**Comment by markelog** [comment]
Nothing, it is landed.

If you like, you can port https://github.com/jscs-dev/node-jscs/commit/2b6a93cb0afed0b4bd401bb626f4aeca17f32681 commit to the require rule.

**Comment by Francisc** [comment]
Thanks, didn't realize it was merged.
I would like to help with the `require` rule, but I can't give a proper ETA (`disable` took me more than it should have), so I'll have to pass this time.

**Pull request closed without merging**
