### PR TITLE
Misc: update esprima to 2.5.0

### PR DESCRIPTION
**Pull request by hzoo**

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
LGTM

**Comment by zxqfox** [comment]
:+1:

**Comment by mrjoelkemp** [comment]
Yeah, we haven't added any functionality directly with this bump, so it's a patch. If we had esprima aa a caret dep, users would get it immediately. Not seeing why it shouldn't qualify for a patch.

**Comment by mikesherov** [comment]
Esprima 2.5.0 brings with it all remaining ES6 funtionality. Technically, this is for a minor version considering it has new features, and some may consider allowing es6 grammar when they haven't asked for it to be a bug.

**Comment by mrjoelkemp** [comment]
> some may consider allowing es6 grammar when they haven't asked for it to
be a bug.

Based on our policy, yes, that's a minor bump. Good point.

**Comment by hzoo** [comment]
Ok I guess this can move to a 2.1.0 milestone

**Pull request closed without merging**
