### PR TITLE
New rule: require-newline-before-single-statements

### LINKED ISSUE #1829: [[FEAT]] requireNewlineBeforeSingleStatements
Consider these options:
```json
{
    "requireNewlineBeforeBlockStatements": false,
    "requireCurlyBraces": false
}
```
I'd like to enforce this style:
```js
// bad
if (x) doX();
else doY();

// good
if (x)
    doX();
else
    doY();
```

or is this a case of me being too peculiar?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27088117-feat-requirenewlinebeforesinglestatements?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by schempy**
requireNewLineBeforeSingleStatements: New rule

Enforce newlines for expression statements within if/else 

Fixes #1829 - issue

### CODE REVIEW

**Comment by markelog** [comment]
Hm, maybe `requireNewlineBeforeSingleStatementsInIf` name could be more explanatory?

**Comment by schempy** [comment]
Sure, that makes sense. Could also allow options to work with if/else, for etc... Don't want to make it more complicated than it needs. What do you think?

**Comment by markelog** [comment]
> Could also allow options to work with if/else, for etc...

I think we can consider using different rule for that?

**Comment by schempy** [comment]
Sure another rule for those makes sense. I'll change the rule name to be ```requireNewlineBeforeSingleStatementsInIf```

**Comment by schempy** [comment]
I changed the rule name to ```requireNewlineBeforeSingleStatementsInIf``` If things look OK I can squash the commits if you'd like.

**Pull request closed without merging**
