### PR TITLE
spacesInsideBrackets: do not get confuse with block comments

### LINKED ISSUE #1749: SpacesInsideBrackets and block comments
Should not show the error for the case like this - 
```js
[ "test_fast" /*, "promises-aplus-tests"*/ ]; // require
["test_fast"/*, "promises-aplus-tests"*/]; // disallow
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26403357-spacesinsidebrackets-and-block-comments?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by markelog**
Fixes #1749

### CODE REVIEW

**Comment by hzoo** [comment]
More rules that need includeComments :+1:

**Comment by markelog** [comment]
Like what?

**Comment by hzoo** [comment]
Sorry, worded that badly - just noting a lot of rules might need it and this is one of them. It's good you reported/fixed it.

**Comment by markelog** [comment]
Yeah, i get it, thought you might something specific in mind :)

**Pull request closed without merging**
