### PR TITLE
Fix reporter name in error message (fixes #1603)

### LINKED ISSUE #1603: Bug: wrong error message when reporter doesn't found
Command:

```
jscs . -r foo
```

Output:

```
Reporter "null" doesn't exist.
```

Expected:

```
Reporter "foo" doesn't exist.
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25282921-bug-wrong-error-message-when-reporter-doesn-t-found?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lahmatiy**
Output correct reporter name in error message when reporter doesn't found

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Seems like our tests just check for an error code. If we really wanted to test this change, we could enhance https://github.com/jscs-dev/node-jscs/blob/master/test/specs/cli.js#L433-L444 to check the error message. 

Mind giving that a try?

**Comment by lahmatiy** [comment]
I'm not sure we need to test it. Otherwise all messages should be tested.
And actually I don't know how to get printed message. Believe console patching is not good aproach.  Any ideas?

**Comment by markelog** [comment]
> I'm not sure we need to test it. Otherwise all messages should be tested.

Yeah, they should be all tested and believe we do that

> And actually I don't know how to get printed message. Believe console patching is not good aproach. Any ideas?

Stubbing is the only way, we do that all over the place

**Comment by mrjoelkemp** [comment]
ping @lahmatiy. Would love to include this for the 2.1.0 release happening on Monday. Any chance the tests could be added by then?

**Comment by markelog** [comment]
Okay, i added tests, thank you @

**Pull request closed without merging**
