### PR TITLE
requireSpaceBeforeDestructuredValues: require space after colon in ob…

### LINKED ISSUE #2074: requireSpaceBeforeDestructuredValues
Name can/should be changed. (http://jscs.info/rule/disallowSpaceBeforeObjectValues)

Require space after colon in object destructuring. Ref https://github.com/dockyard/ember-suave/issues/56

```js
// bad
const { String:EmberString } = Ember;

// good
const { String: EmberString } = Ember; 
```

### PR DESCRIPTION
**Pull request by fxmaxvl**
…ject destructuring

Fixes #2074

### CODE REVIEW

**Comment by hzoo** [comment]
If we want to cover all cases (although rare), you can do destructuring like `({a: asdf, b: asdf2} = {a:1, b:2});` as well

**Comment by fxmaxvl** [comment]
oh, yes, you're right.
([ {a: asdf, b: asdf2} ] = [ {a:1, b:1} ]);
and this case is also possible.
I'll fix it

**Comment by markelog** [comment]
It seems there is a jshint issue there?

**Comment by fxmaxvl** [comment]
lib/errors.js: line 1, col 5, 'assert' is defined but never used.
1 error
---
this not in mine changes, why it happens?

**Comment by markelog** [comment]
Oh, yeah, sorry about, anyway, merged, thank you!

**Pull request closed without merging**
