### PR TITLE
requirePaddingNewLinesAfterBlocks: ignore jsx tags when checking for

### LINKED ISSUE #2008: requirePaddingNewLinesAfterBlocks in JSX
Currently this rule says that this is a problem:

```
var foo = (
  <div
    ref={function() {
    }}
  >
    foo
  </div>
);
```

but this is accepted:

```
var foo = (
  <div
    ref={function() {
    }}

  >
    foo
  </div>
);
```

There should probably be an exception for JSX.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28907614-requirepaddingnewlinesafterblocks-in-jsx?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by bomatson**
newlines after blocks

Fixes #2008 - issue

### CODE REVIEW

**Comment by markelog** [comment]
@TheSavior would you mind checking it against your code?

**Comment by bomatson** [comment]
@markelog why was this closed? The test case matched @TheSavior's code

**Comment by TheSavior** [comment]
It looks like he merged your PR in commit 95dc04b

**Comment by hzoo** [comment]
If its like "closed this pull request in" its because the way this project does merges is by doing rebase instead of the github merge button (check the commits history)

**Comment by bomatson** [comment]
awesome thanks @TheSavior @hzoo !

**Pull request closed without merging**
