### PR TITLE
Docs: Modify Inline Comments

### LINKED ISSUE #1451: Docs: Document that error suppression only holds for the current file
If you want to ignore the entire file, just do:

```js
// jscs: disable
```

No need to add `// jscs: enable` at the end of the file.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/21683276-docs-document-that-error-suppression-only-holds-for-the-current-file?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by oredi**
Modify "Disabling All Rules" description and added new documentation on how to disable rule checking for the entire file

    Fixes #1451 

Please take note that one of the test is failing in the latest Master. The error details are as per the image

image

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
@oredi You need to `npm install` on the master branch

**Comment by mrjoelkemp** [comment]
LGTM

**Comment by oredi** [comment]
@mrjoelkemp Thanks for the pointer and sorry for the newbie mistake :blush:.  The tests and coverage ran fine now

**Comment by mrjoelkemp** [comment]
@oredi Happened to me many many times :) Adding an `npm install` to a post-checkout git hook should solve that problem.

**Pull request closed without merging**
