### PR TITLE
`requireSemicolons`: check for `ClassProperty`

### PR DESCRIPTION
**Pull request by hzoo**
Ref https://github.com/babel/babel/pull/3225

### CODE REVIEW

**Comment by markelog** [comment]
Wow, didn't even know you could do that. 
LGTM

**Comment by michaelficarra** [comment]
It's going to be hilarious when the babel people figure out this is a bug and the semicolon-free people need a semicolon remover.

**Comment by markelog** [comment]
Oh right, we need the same action for `disallowSemicolons` )

**Comment by markelog** [comment]
When prop without semicolon will became a correct syntax that is

**Comment by hzoo** [comment]
Well when that happens it sounds like a `good first bug`/`beginner friendly` issue to me! :smile:

**Comment by michaelficarra** [comment]
@markelog It is already valid to omit semicolons after class properties in most cases.

**Comment by markelog** [comment]
@michaelficarra

[Really](https://github.com/babel/babel/pull/3225#issuecomment-170056158)?

> semicolons are required always.

**Comment by michaelficarra** [comment]
[Really](https://github.com/babel/babel/pull/3225#issuecomment-170155425).

**Comment by markelog** [comment]
Don't see any clarification on the ASI in original link i provided, but judging by the interesting [original](https://github.com/jeffmo/es-class-fields-and-static-properties/issues/25) discussion and rules of ASI you should be right.

Which means babel pr was indeed falsy (not this pr though) and that we can add same opposite logic to `disallowSemicolons` rule.

Thanks for playing!

**Comment by michaelficarra** [comment]
You're welcome. Don't forget about [this case](https://github.com/jeffmo/es-class-fields-and-static-properties/issues/26#issuecomment-170138501) which I hadn't thought of at first.

**Comment by flying-sheep** [comment]
[here](https://github.com/jeffmo/es-class-fields-and-static-properties/issues/26#issuecomment-177720642)’s the ASI clarification

**Pull request closed without merging**
