### PR TITLE
New Rule: disallowIdenticalDestructuringNames

### LINKED ISSUE #1081: New Rule: Disallow Identical Destructuring Names?
ES2015's destructuring assignment has a [shorthand form][1] - it would be cool if JSCS could flag up code that could be shortened by using this syntax.

For example, the new rule would flag up this code:

    var {left: left, top: top} = this.refs.container.getDOMNode().getBoundingClientRect();

But allow the following lines:

    var {left, top} = this.refs.container.getDOMNode().getBoundingClientRect();
    var {left: someName, top: otherName} = this.refs.container.getDOMNode().getBoundingClientRect();

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Simple_example_2

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8684500-new-rule-disallow-identical-destructuring-names?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by hzoo**
Fixes #1081
Closes gh-1844

cc @iamdanfox

### CODE REVIEW

**Comment by markelog** [comment]
Still `WIP`?

**Comment by hzoo** [comment]
No tests are passing now so I think I'm good

**Comment by hzoo** [comment]
If anyone can review first?

**Comment by markelog** [comment]
all good

**Comment by hzoo** [comment]
Ok merging then

**Pull request closed without merging**
