### PR TITLE
New rule: add JSDoc rules

### LINKED ISSUE #986: Execution without options
If project doesn't have jscs config and If jscs cli tool is executed without options but with path argument - `jscs <files>`. What should we do?

Two possible ways:
1. Apply rules from "default" preset, like with `go fmt`, `standart` npm <a href="https://github.com/feross/standard">package</a> or with python pep8 <a href="http://pep8.readthedocs.org/en/latest/intro.html">tool</a>. While proposing to use auto-config option at the end of error list.
2. Enable auto-config option by default.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8192214-execution-without-options?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1359: Make jsDoc plugin part of the jscs dist
It could be in another repo, but a dependency of jscs.

/cc @zxqfox 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/14206447-make-jsdoc-plugin-part-of-the-jscs-dist?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by markelog**
Documentation synchronization is an issue, plus jscs-dev/jscs-dev.github.io/issues/26 jscs-dev/jscs-dev.github.io/issues/25 are also unpleasant.

Fixes #1359

@zxqfox @mdevils thoughts?

### CODE REVIEW

**Comment by zxqfox** [comment]
Oh, thanks for that. But, hmmm... ;-) it's dirty! Do we really want to load the only rule and copy-paste docs like that?

What I really want here:
- change file structure a little to have splitted docs and code (also tests maybe?);
- 

File structure could be then like:
```sh
rules/
  rule1/
    index.js
    index.md
  rule2.js # with current structure
```

And we could load them as we do it now but `*.md` files would be easier to load to build and also they will be highlighted, we could check them separately, etc.

And with that structure we have to build as many plugins as we need.

I'm not sure also that we should register `jsDoc` as a single rule. I would like to see it like in eslint plugins: `jsdoc/rule1`. But this issue is like so very complicated to solve that nobody want to open that pandora box. :smirk_cat:

Btw. Why you stick to 1.0.0?

Looks nice at all. If everybody fine with that method — ok.

**Comment by markelog** [comment]
> Do we really want to load the only rule and copy-paste docs like that?

Well, i don't, i really don't like that, but this is currently a one way to do that, we could do hierarchy, but that would mean site would need to support that and we would need to dynamically move it from `node_modules` 

> I'm not sure also that we should register jsDoc as a single rule. I would like to see it like in eslint plugins: jsdoc/rule1. But this issue is like so very complicated to solve that nobody want to open that pandora box.

Would you like to open that? Would be really cool, if you did.

> Btw. Why you stick to 1.0.0?

Because if you release new version, you might change documentation, but this dup will not change :-(

**Comment by zxqfox** [comment]
> Because if you release new version, you might change documentation, but this dup will not change :-(

But the last version is 1.1.0

> Would you like to open that? Would be really cool, if you did.

Would be cool if anyone will do it ;-) Let's listen to guys and @mdevils to decide what to do here.

p.s. I fear this react and webpack used in our site ;-(

**Comment by markelog** [comment]
> p.s. I fear this react and webpack used in our site ;-(

Join the club, but common, this is nothing for bemtree priv.js veteran :-)

**Comment by zxqfox** [comment]
@markelog Nice joke ;-D

**Pull request closed without merging**
