### PR TITLE
Rename rules

### LINKED ISSUE #1549: Should we rename "var" and "decl" rules to "variable" and "declaration" for consistency?
In the following rules, "variable" is spelled correctly:

- `requireLineBreakAfterVariableAssignment`
- `requirePaddingNewLineAfterVariableDeclaration`

In the following rules, "declaration" is spelled correctly:

- `disallowFunctionDeclarations`
- `disallowSpacesInFunctionDeclaration`
- `requireFunctionDeclarations`
- `requirePaddingNewLineAfterVariableDeclaration`
- `requireSpacesInFunctionDeclaration`

But inconsistently, "variable" and "declaration" are misspelled as "var" and "decl" in the following rules:

- `disallowMultipleVarDecl`
- `requireMultipleVarDecl`

And the new rule `requireVarDeclFirst` carries this inconsistency forward.

Perusing the rules reveals that all other rule names are also spelled correctly. You should maintain this consistency by renaming the following rules:

- `disallowMultipleVarDecl` becomes `disallowMultipleVariableDeclarations`, with the old name as an obsolete alias
- `requireMultipleVarDecl` becomes `requireMultipleVariableDeclarations`, with the old name as an obsolete alias
- `requireVarDeclFirst` becomes `requireVariableDeclarationFirst`

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/24687849-should-we-rename-var-and-decl-rules-to-variable-and-declaration-for-consistency?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jacksonrayhamilton**
Fixes #1549.

### CODE REVIEW

**Comment by jacksonrayhamilton** [comment]
Build failed due to "Coveralls is in Read Only mode while we work on updating the system. Sorry for the inconvenience." We can try again soon but should be good to go.

**Comment by markelog** [comment]
Oh man, i wish you would ask before submitting this, we will not rename rules in 2.0, this planned only for 3.0 :-(

**Comment by jacksonrayhamilton** [comment]
@mrjoelkemp asked "Would you like to submit a PR that renames the rules?" So I do not understand your release schedule.

If you are worried about breakage, we can just silently alias indefinitely.

**Comment by markelog** [comment]
Yes, also @mrjoelkemp wrote
>  I'm not sure we have a lot of breaking, rule renaming going on in 2.0. @markelog, do you think we should maintain backCompat for this even if the rename lands in 2.0?

and Mike added 
> But there was also a whole lot more renaming we were going to do for 2.0, but now that we haven't released in so long, I fear its counterproductive to do this now as it'll delay a 2.0 for longer than it's already been delayed. This is at least one reason I wanted a 1.14

**Comment by markelog** [comment]
> If you are worried about breakage, we can just silently alias indefinitely.

We would need to do something with documentation, maintain renamed rules, show deprecate notice, etc.

**Comment by jacksonrayhamilton** [comment]
Well, I am confused. No one said not to do it. It sounded more like you guys wanted to delay a release to make more changes like this, actually.

**Comment by markelog** [comment]
> No one said not to do it

Really?

> I fear its counterproductive to do this now

I guess this is misunderstanding, in any case, i'm sorry, you did all that work, but we really can't delay 2.0 anymore

**Comment by jacksonrayhamilton** [comment]
Let's have other contributors weigh in; not because I am hoping for a different answer, but because it's possible either one of us misunderstood what was said.

**Comment by markelog** [comment]
The thing is, we should release in couple hours, everything is prepared for it, what you asking is to delay the release

**Comment by mikesherov** [comment]
@jacksonrayhamilton thanks for contributing this patch. I'd like to defer this work to 3.0 while we refine our deprecation strategy.

**Comment by jacksonrayhamilton** [comment]
Fair enough. It should be easy to rebase or do it over again anyway. I will make sure to double-check before submitting changes again.

**Comment by markelog** [comment]
Thank you @jacksonrayhamilton and sorry again for this misunderstanding

**Comment by mikesherov** [comment]
@jacksonrayhamilton no worries. We keep it pretty loose, there's a lot of opportunities for the occasional misunderstanding. No harm, no foul by submitting this PR. Thanks again for contributing.

**Pull request closed without merging**
