### PR TITLE
Misc: set default value of maxErrors option to 50

### LINKED ISSUE #681: Change the default maxError to 50
<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5275604-change-the-default-maxerror-to-50?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by markelog**
* Set default value of maxErrors option to 50
* Do not consider maxErrors value at autofix execution
* Rename testsuites of root modules
  (since they should point to the path of module their testing)

Fixes #681

/cc @mikesherov @mdevils

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Not seeing new logic about how this prevents autofix from being affected. A test would suffice for reassurance. 

Lgtm, but this is for sure a breaking change. So merge in the 2.0 branch? Still haven't heard if we're doing 2.0 first or 1.14.

**Comment by markelog** [comment]
> A test would suffice for reassurance.

For sure, will add one

> Lgtm, but this is for sure a breaking change. So merge in the 2.0 branch? Still haven't heard if we're doing 2.0 first or 1.14.

That is the question, isn't it :-). It is good thing that we have two branches, there is three things need to be done, in order to release 2.0

1. https://github.com/jscs-dev/node-jscs/issues/986
2. #1359
3. https://github.com/jscs-dev/node-jscs/issues/1353

#986 requires more discussion, so it might closed as won't fix, others, mostly depend on free time of the 
@zxqfox and @hzoo.

It seems #1359 is pretty easy to do and @hzoo solved most of complicated issues of #1353, one thing is left is one little step.

So i'm thinking, if we could do those three things quickly, like week at most, we might as well, release 2.0.

**Comment by hzoo** [comment]
https://github.com/jscs-dev/node-jscs/pull/1494 left on the actual 1.14 milestone but I'm assuming there might be a few more?

**Comment by mrjoelkemp** [comment]
Thanks for the explanation @markelog. 2.0 on 7/14. Sounds like a plan.

**Pull request closed without merging**
