### PR TITLE
Allow async function expressions

### PR DESCRIPTION
**Pull request by MikeMcElroy**

### CODE REVIEW

**Comment by MikeMcElroy** [comment]
Passes on my local machine, and the travis error looks a lot like an error I was hitting a while back, but I fixed that.

**Comment by hzoo** [comment]
Looks good - I think we'll need to fix any errors with async, generator, arrow functions soon. Don't know if that needs to happen in this PR

**Comment by MikeMcElroy** [comment]
I really have no idea why it's failing on travis-ci and succeeding on appveyor.  Thoughts, @hzoo?

**Comment by hzoo** [comment]
Looks like 2 tests are failing?

```
1) rules/disallow-spaces-in-function-expression beforeOpeningRoundBrace should not report missing space before round brace in FunctionExpression:
      AssertionError: false == true
      + expected - actual
      -false
      +true
      
      at Context.<anonymous> (test/specs/rules/disallow-spaces-in-function-expression.js:39:13)
  2) rules/require-spaces-in-function-expression beforeOpeningRoundBrace should report missing space before round brace in FunctionExpression:
      AssertionError: false == true
      + expected - actual
      -false
      +true
      
      at Context.<anonymous> (test/specs/rules/require-spaces-in-function-expression.js:39:13)
```

**Comment by MikeMcElroy** [comment]
So I ran across that problem (same line numbers and everything) earlier in the PR.  I force-pushed my changes, and I maybe had the PR open at that point, so maybe something got screwed up with Travis?  The Appveyor works fine, and locally the tests run OK.  I'm not sure how best to debug the issue solely on Travis.

**Comment by hzoo** [comment]
Yeah it passes locally so should be good.

**Comment by zxqfox** [comment]
@MikeMcElroy Thanks for contribution!

LGTM

**Comment by hzoo** [comment]
We'll need to add the same changes to `SpacesInNamedFunctionExpression`, `SpacesInAnonymousFunctionExpression, and `SpacesInFunction` but we can go ahead and merge then?

**Pull request closed without merging**
