### PR TITLE
Added JSON reporter

### PR DESCRIPTION
**Pull request by romanblanco**
New reporter that returns errors in JSON format

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Nice work here @romanblanco. Thanks for contributing! LGTM

**Comment by markelog** [comment]
It seems amount of reporters grows pretty fast, we need to be more conservative here.  

LGTM

**Comment by markelog** [comment]
btw, what is use-case for this?

**Comment by romanblanco** [comment]
@markelog we need JSON output to be able to integrate jscs to GitHub bot for pull request monitoring.

**Comment by markelog** [comment]
Isn't that easier to use API for that sort of thing? What do you do for other runners?

**Comment by markelog** [comment]
?

**Comment by romanblanco** [comment]
@markelog What API do you mean?

**Comment by markelog** [comment]
Lets start from the other end, how do get that info from the other linters? Like jshint, eslint?

**Comment by markelog** [comment]
fyi, we probably gonna release this with 2.1 version, i would like to just better understand your use-case

**Comment by romanblanco** [comment]
@markelog till this time, we only used [haml-lint](https://github.com/brigade/haml-lint) and [rubocop](https://github.com/bbatsov/rubocop) linters in our GitHub bot (which has similar use to https://www.houndci.com/), as you can see [here](https://github.com/ManageIQ/miq_bot/blob/master/app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb#L30). They both provide JSON output. We would like to use other linters, which means, we need to either make a wrapper to output linter results in JSON, or add another reporter right into linter.

**Comment by markelog** [comment]
And you don't want to provide global/relative reporter for the `--reporter` flag?

**Comment by romanblanco** [comment]
Which global/relative reporter flag you got on mind? I don't quite understand that question.

**Comment by markelog** [comment]
See http://jscs.info/overview.html#-reporter-r, like https://github.com/wurmr/jscs-teamcity-reporter

**Comment by romanblanco** [comment]
Well, yes. I probably could specify my own reporter, if it would be problem to add another into node-jscs. I didn't noticed this option before.

**Comment by markelog** [comment]
Thank you!

**Pull request closed without merging**
