### PR TITLE
validateIndentation: Add support for 'offset' switch cases

### PR DESCRIPTION
**Pull request by mtp401**
'offset' switch cases are cases indented by a half indent. Example
(indentSize = 4):
```js
switch (val) {
  case "1":
    a();
    break;
  default:
    b();
    break;
}
```

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
cc @mikesherov

**Comment by markelog** [comment]
Hm, could you show an example of such code? Is there any code-style that recommends to do that? Is there any editors/IDE that do that?

**Comment by mtp401** [comment]
Google C++ style (and by derivation Google JavaScript Style) recommends this convention. See https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Loops_and_Switch_Statements

**Comment by markelog** [comment]
Not exactly, they recommend to use 2 spaces indentation, so 2 not only for switches but for every block constuction

**Comment by markelog** [comment]
Okay, if you want to continue this discussion, ping us up

**Pull request closed without merging**
