### PR TITLE
file extension fixes. Fixes #2275 #2273

### LINKED ISSUE #2275: not possible to ignore '.js' files with fileExtensions #2273
https://github.com/graingert/jscs-error
With only .es files included:
```
{
    "preset": "airbnb",
    "fileExtensions": ['.es']
}
```
JSCS still complains if .js files have errors:

```
$ npm install
$ ./node_modules/.bin/jscs src
Unexpected character '#' (3:4) at src/old.js :
     1 |sdlkfjhskldjads
     2 |asdf
     3 |asdf#
------------^
     4 |asdf
     5 |asdf


1 code style error found.
```

### PR DESCRIPTION
**Pull request by graingert**
Fixes #2275 #2273

### CODE REVIEW

**Comment by markelog** [comment]
Decided to fix this a bit differently, would appreciate a second look though - https://github.com/jscs-dev/node-jscs/commit/0d027a7b4a95c7c349f57ffd37f10e497d66a5d4

**Comment by graingert** [comment]
@markelog this doesn't fix #2273

**Comment by markelog** [comment]
It's not supposed to

**Comment by graingert** [comment]
Can you reopen #2273 so I can recreate the PR to fix it?

**Comment by markelog** [comment]
I don't know man, everywhere i looked, like https://en.wikipedia.org/wiki/File_format#Filename_extension,  https://en.wikipedia.org/wiki/Filename_extension https://docs.python.org/2/library/os.path.html#os.path.splitext,
`path.extname` of node.js, 
http://ruby-doc.org/core-2.2.0/File.html#method-c-extname,
https://golang.org/pkg/path/filepath/#Ext
and others... give me the same result

**Comment by markelog** [comment]
You can probably workaround it with something like this though - 
```js
"excludeFiles": ["**/!(*.es2015.js)"]
```

**Comment by graingert** [comment]
@markelog nope, that seems to exlude all files.

**Comment by markelog** [comment]
It should ignore all files which ends with `.es2015.js`

**Comment by graingert** [comment]
@markelog I know. But it seems to exclude all files

**Comment by markelog** [comment]
Oh shoot, typo there, it *shouldn't* ignore files which ends with  `.es2015.js`

**Comment by graingert** [comment]
Sorry I doubled the mistake and thought that's what you said originally. It still ignores all files

**Comment by markelog** [comment]
Weird, works for me

**Comment by markelog** [comment]
Maybe you could illustrate it with test repo?

**Comment by graingert** [comment]
Yeah will do

**Pull request closed without merging**
