### PR TITLE
disallowEmptyBlocks: should not report empty arrow blocks

### PR DESCRIPTION
**Pull request by jakezatecky**
Similar to #169 and #174, this just extends the logic to arrow functions.

### CODE REVIEW

**Comment by hzoo** [comment]
Looks good.

Also do we want to make a helper for functions (`FunctionDeclaration`, `FunctionExpression`, `ArrowFunctionExpression`)? Maybe some other rules need to be updated with ArrowFunctionExpression

**Comment by jakezatecky** [comment]
It probably makes sense to add a helper, but I'll leave that for the more experienced. It is also probably the case that other rules also need to be updated with `ArrowFunctionExpression` blocks (such as `validateAlignedFunctionParameters`).

**Comment by hzoo** [comment]
@jakezatecky If it's not hard to add we might as well include it here too (the other rules), otherwise we can just do another PR later (if you want to, or I'l do it).

**Comment by jakezatecky** [comment]
I certainly can go and add the arrow function-related modifications to other rules. I should be able to get some time closer toward the end of this week.

**Comment by zxqfox** [comment]
@jakezatecky Thanks! Good luck with that ;-)

**Comment by markelog** [comment]
@jakezatecky still interested?

**Comment by jakezatecky** [comment]
Sorry for the lack of progress. Yes, I'm still interested and will (soon) work on updating the other rules to account for arrow functions.

**Comment by markelog** [comment]
No worries :-)

**Comment by markelog** [comment]
Oh, i see you added a commit, but coverage decreased, would you mind adding more tests and rebase?

**Comment by markelog** [comment]
Hm, didn't find a problem with the coverage, anyway, thank you!

**Pull request closed without merging**
