### PR TITLE
validateNewlineAfterArrayElements: --fix now works for this rule

### LINKED ISSUE #2065: running --fix with a validateNewlineAfterArrayElements rule doesnt apply the fix
Hi guys,

first of all my jscsrc: 
```json
{
  "preset": "airbnb",
  "validateNewlineAfterArrayElements": {
    "maximum": 1
  }
}
```

I'm currently bumping into this situation:
I have the following array:
```js
const someArr = [{
    test: 'test',
  }];
```
Linting this will warn me that there should be a new line after the [ and before the ].
Unfortunately trying to --fix this array will turn it into:
```js
  const someArr = [{
    test: 'test',
  },];
```
It will append the trailing comma to the only object since that is one of the rules of Airbnb. But it doesnt put the newlines in. 

I think this is a bug or am I missing something?

### PR DESCRIPTION
**Pull request by joerideg**
Fixes #2065

### CODE REVIEW

**Comment by markelog** [comment]
Would you mind adding basic tests for autofixing? See example - https://github.com/jscs-dev/node-jscs/blob/c704e9e0713c5462a61dac309a6e6abd30098545/test/specs/rules/disallow-semicolons.js#L68-L74

**Comment by joerideg** [comment]
Will do!

**Comment by joerideg** [comment]
Quick update: Quite busy with work but will hopefully get to the test tomorrow or thursday.

**Comment by markelog** [comment]
Friendly ping

**Comment by joerideg** [comment]
I'll get around to it monday! Cheers

**Comment by hzoo** [comment]
I can do this today so don't worry about it

**Comment by hzoo** [comment]
Ok added tests in https://github.com/jscs-dev/node-jscs/commit/b86c8c28a8d5a0b95f12c85da260174a0f3b9922

**Comment by joerideg** [comment]
Cool! :) Can I remove my fork now? (this is my first pull request ever)

**Comment by markelog** [comment]
Yeah and congrats on your first contribution!

**Comment by joerideg** [comment]
Thanks!

**Comment by hzoo** [comment]
@joerideg Thanks so much for your PR (and first contribution)!

Ah I would recommend that (in the future) you create a branch 
screen shot 2016-01-25 at 7 43 21 am
instead of sending a PR from your master branch.

Then you can just delete that branch (or leave it there). You don't really want to remove your fork (unless you aren't planning on contributing to the repo ever again). Sending your PR's through seperate branches allows you to have multiple PR's at the same time if that becomes necessary (and it's the recommended way to do so).

screen shot 2016-01-25 at 7 45 11 am

**Comment by joerideg** [comment]
Ill keep that in mind, thanks!

**Pull request closed without merging**
