### PR TITLE
Docs: Fixed typo, update link for clarity/correct URL

### PR DESCRIPTION
**Pull request by kaicataldo**

### CODE REVIEW

**Comment by hzoo** [comment]
:+1:

**Comment by zxqfox** [comment]
:+1: Thanks!

**Comment by kaicataldo** [comment]
Whoops, typo in my typo fix (derp). Fixed now.

**Comment by mrjoelkemp** [comment]
Really not sure why coveralls is complaining about doc-only builds: https://travis-ci.org/jscs-dev/node-jscs/jobs/74479224. This and another doc-only PR keep failing :(

@markelog should we still merge? I assume this would break master, unfortunately.

**Comment by hzoo** [comment]
What do we think about getting `Docs` commits to add `[ci skip]` to the commit message?

**Comment by markelog** [comment]
This one failed because of the force push, so yeah, pretty safe to land.

> What do we think about getting Docs commits to add [ci skip] to the commit message?

Doesn't hurt to run on every commit

**Comment by mrjoelkemp** [comment]
Thanks for contributing @kaicataldo. 

Thanks for the confirmation @markelog.

**Pull request closed without merging**
