### PR TITLE
requireVarDeclFirst: Fixing an edge case

### LINKED ISSUE #2022: requireVarDeclFirst error when comment in function expression
Rule that has issue: "requireVarDeclFirst: true"
Code that will make jscs exhibit the issue:
.jscsrc file:

    {
      "requireVarDeclFirst": true
    }

test.js

    var test = function() {
      var color = "grey";
      // This is a comment
    };
    var test2 = "string";

node command:

    jscs test.js

The task will report an error for the line with the second assignment, but if I remove the comment in the function expression, the error goes away.

Using jscs 2.7.0
Operating system: Windows 7 64-bit

### PR DESCRIPTION
**Pull request by kepta**
In this edge case the comments from previous block scope were being taken and
a false positive error was thrown.

Fixes #2022 - issue

### CODE REVIEW

**Comment by markelog** [comment]
> Coverage decreased (-0.02%) to 99.308%

You need to add tests

**Comment by kepta** [comment]
Oh I am so sorry for that.

**Comment by markelog** [comment]
Totally okay, just bring it up

**Comment by markelog** [comment]
Nicely done, thank you!

**Pull request closed without merging**
