### PR TITLE
Docs: add if autofixable to rule descriptions

### PR DESCRIPTION
**Pull request by hzoo**
Although this is putting if rules are fixable rather than not - https://github.com/jscs-dev/node-jscs/issues/2014

### CODE REVIEW

**Comment by markelog** [comment]
> Although this is putting if rules are fixable rather than not - #2014

Why?

**Comment by hzoo** [comment]
I think merging as is should be fine at this point @markelog?

**Comment by markelog** [comment]
I think no, since this pull is pretty old and i'm would go other way around with it

**Comment by hzoo** [comment]
It would make it easy to compare whats autofixable in eslint/jscs given that's how they have it

**Comment by markelog** [comment]
We would need this pull to be updated then, although i'm still not sure why it can't be other way around

**Comment by zxqfox** [comment]
It can be other way around, but in that way it'll take more time. Isn't it a wasting?

**Comment by hzoo** [comment]
Yes unless anyone is going to actually do that work, we should just merge (my point is that it's already done)

**Comment by markelog** [comment]
> my point is that it's already done

https://en.wikipedia.org/wiki/Sunk_costs

after fourth months it needs to be reevaluated anyhow, which means you have go through all the rules again and jscs has more rules that are autofixable then not

**Comment by hzoo** [comment]
Why does it have to be reevaluated in four months? we aren't adding more anytime soon

**Comment by markelog** [comment]
I'm not sure if all rules that right now are marked as fixable are indeed fixable, some rules didn't have any autofix tests, since they used tested versions of general methods, but with 3.0 rewrite we heavily change every single rule and removed some general methods and for some introducted `_fix` method.

Plus we need to account for new rules.

**Comment by hzoo** [comment]
k

**Pull request closed without merging**
