### PR TITLE
preset google add missing rules

### PR DESCRIPTION
**Pull request by christophehurpeau**
According to the [documentation](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml), some rules are missing. There are not always explicit but the code examples seems to match these rules

### CODE REVIEW

**Comment by cyrilf** [comment]
Great! :+1:

**Comment by markelog** [comment]
Could you provide links to the doc for every rule you added?

**Comment by christophehurpeau** [comment]
Here are the links to the documentation:

`"disallowKeywords": ["with"]`: [https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=with___{}#with___{}](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=with___{}#with___{})

`"requireCapitalizedConstructors": true`: [here](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Naming#Naming), the valid name is : `ClassNamesLikeThis, EnumNamesLikeThis`

For the following rules, there are no explicit rules but the documentation follow them:

`"disallowSpaceAfterObjectKeys": true` and `"requireSpaceBeforeObjectValues": true`: You can find [here](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Array_and_Object_literals#Array_and_Object_literals) the documentation about objects literal, and the valid syntax is:

```
var o = {};

var o2 = {
  a: 0,
  b: 1,
  c: 2,
  'strange key': 3
};
```

`"disallowSpacesInFunctionExpression": { "beforeOpeningRoundBrace": true }`: For example [here](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=for-in_loop#for-in_loop) and [here](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Closures#Closures), all functions do not have space before round brace : 
`var foo = function() {};`, `function bar(a, b) {`

`"disallowSpacesInCallExpression": true`: For example [here](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Closures#Closures) : `element.onclick = bar(a, b);`

`"requireDotNotation": true`: You can find [here](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Array_and_Object_literals#Array_and_Object_literals) the documentation about objects literal, and the valid syntax is:

```
var o2 = new Object();
o2.a = 0;
o2.b = 1;
o2.c = 2;
o2['strange key'] = 3;
```

It is a deny rule, but there are not talking about syntax but assignation. You can also find another example [here](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Naming#Naming) : 

```
/** @enum {string} */
some.long.namespace.Fruit = {
  APPLE: 'a',
  BANANA: 'b'
};

myapp.main = function() {
  var Fruit = some.long.namespace.Fruit;
  switch (fruit) {
    case Fruit.APPLE:
      ...
    case Fruit.BANANA:
      ...
  }
};
```

`"validateParameterSeparator": ", "`: You can find an example [here](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Closures#Closures):
```
function foo(element, a, b) {
  element.onclick = bar(a, b);
}

function bar(a, b) {
  return function() { /* uses a and b */ };
}
```

**Comment by markelog** [comment]
Nice, thank you!

> "disallowSpacesInFunctionExpression": { "beforeOpeningRoundBrace": true }: For example here and here, all functions do not have space before round brace : 
var foo = function() {};, function bar(a, b) {

It seems we need to add <a href="http://jscs.info/rule/disallowSpacesInFunctionDeclaration.html">`disallowSpacesInFunctionDeclaration `</a> too?

**Comment by christophehurpeau** [comment]
yes indeed

**Comment by markelog** [comment]
Okay, commit this up, and we are good to go

**Comment by christophehurpeau** [comment]
done :)

**Comment by markelog** [comment]
Thank you!

**Comment by christophehurpeau** [comment]
Thank you :)

**Pull request closed without merging**
