### PR TITLE
(disallow/require)PaddingNewLinesAfterBlocks: Ignoring the end of files

### PR DESCRIPTION
**Pull request by TheSavior**
Fixing an error since we are now adding the EOF token into the mix.

### CODE REVIEW

**Comment by mikesherov** [comment]
:+1: good catch! Have you checked other rules to see if they're affecyed?

**Comment by TheSavior** [comment]
I did a search through for == undefined (to also catch === and !==) and didn't find any other comparisons like this.

**Comment by mikesherov** [comment]
How about `!.*token` regex search?

**Comment by TheSavior** [comment]
Still nope.

There are some `if (!token || !nextToken) {` checks, but those are in the assertions and belong.

There are a couple of rules that use `if(!prevToken)`, but since they are only iterating backwards, we wouldn't have to add a check that stops it when it is EOF instead of on undefined.

It looks like we are all good on adding the EOF token, once we roll out we will definitely want to watch for error reports just in case though.

**Comment by mikesherov** [comment]
:+1:

**Comment by TheSavior** [comment]
Bump?

**Comment by mikesherov** [comment]
Thanks again!

**Pull request closed without merging**
