### PR TITLE
bump esprima-harmony-jscs to 1.1.0-tolerate-import

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by cvrebert** [comment]
I'd need to conduct further testing to be sure, but combined with the existing `tolerant: true` change, this appears to be sufficient to fix #952.

**Comment by mikesherov** [comment]
Ok, let me know when you've finished testing.

**Comment by cvrebert** [comment]
@mikesherov Yup, have confirmed that this finishes fixing #952.

**Comment by cvrebert** [comment]
Any estimate of when the next JSCS release will happen?

**Comment by mikesherov** [comment]
@cvrebert, as soon as we land autoconfiguration, which is almost completed.

**Pull request closed without merging**
