### PR TITLE
Add 'switch' to *newlineBeforeBlockStatements

### PR DESCRIPTION
**Pull request by PaulAnnekov**
https://github.com/jscs-dev/node-jscs/issues/2045

### CODE REVIEW

**Comment by PaulAnnekov** [comment]
So?..

**Comment by hzoo** [comment]
Sorry for the delay! Thanks!

**Comment by PaulAnnekov** [comment]
@markelog waiting for my `nice work, bro` https://github.com/jscs-dev/node-jscs/issues/2045#issuecomment-168816726 :)

**Comment by PaulAnnekov** [comment]
@markelog still waiting for my bro...

**Comment by markelog** [comment]
Sorry, was preoccupied lately, check this out - https://twitter.com/jscs_dev/status/694073841568583682

**Comment by PaulAnnekov** [comment]
@markelog great, 10x :)

**Pull request closed without merging**
