### PR TITLE
requireDotNotation: new value except_snake_case

### PR DESCRIPTION
**Pull request by zxqfox**
Ref #866

### CODE REVIEW

**Comment by zxqfox** [comment]
:up:

**Comment by markelog** [comment]
Could add tests for https://github.com/jscs-dev/node-jscs/pull/868#discussion_r22388356?

**Comment by zxqfox** [comment]
@markelog Rebased, reverted accidentally dropped docs for es3 flag (website commit), added test for case `___`.

**Comment by markelog** [comment]
Merged, although, i doubt we would ever need `isSnakeCased` and `trimUnderscores` methods somewhere else.

Let's put a pin on those

**Comment by zxqfox** [comment]
@markelog e.g. we don't have a semantic opposite to `requireCamelCaseOrTitleCase` rule. ;-)

**Pull request closed without merging**
