### PR TITLE
validateIndentation: add option to ignore comments

### LINKED ISSUE #1215: an option to ignore indentation validation for comments
This feature should be able to silence the error on the bottom:

```
$ cat a.js 
var a = Math.random();
if (a < 0.5) {
  // testing jscs comment indentation
  a = 0;
//  a = 0.5;
}
$ cat cfg.json 
{
  "validateIndentation": 2
}
$ ./node_modules/.bin/jscs -c cfg.json a.js 
Expected indentation of 2 characters at a.js :
     3 |  // testing jscs comment indentation
     4 |  a = 0;
     5 |//  a = 0.5;
----------^
     6 |}
     7 |


1 code style error found.
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10176732-an-option-to-ignore-indentation-validation-for-comments?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by flyingjamus**
Fixes #1215

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Nice work here! 

Lgtm, but @mikesherov is the indentation expert. Will wait for his approval.

**Comment by mikesherov** [comment]
Thanks for contributing! I'm curious as to what the failing tests are... Otherwise, seems reasonable. Good work here.

**Comment by markelog** [comment]
"Indentation expert" sounds peculiar :-), Is that makes sense to move `includeEmptyLines` (with renaming) to `allExcept` option?

**Comment by markelog** [comment]
> I'm curious as to what the failing tests are... 

Coverage... again, so it seems LGTM

**Comment by markelog** [comment]
Thank you

**Pull request closed without merging**
