### PR TITLE
Improve *SpacesInsideParentheses rules

### LINKED ISSUE #836: Ignore/Except Quotes in requireSpacesInsideParentheses
Is it possible to ignore quotes from requireSpacesInsideParentheses?
I'd like to cover this case (https://github.com/rwaldron/idiomatic.js/#type 2.C.1.3) 
```javascript
// Single argument string literal, no space
foo("bar");
```

This doesn't work:
```javascript
"requireSpacesInsideParentheses": {
 "all": true,
 "except": [ "{", "}", "\"" ]
},
```

Any ideas?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7028394-ignore-except-quotes-in-requirespacesinsideparentheses?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by markelog**
* Exclude quotes
* Introduce the `ignoreParenthesizedExpression` option for `requreSpacesInsideParentheses` rule

Fixes #836
Ref #1069

### CODE REVIEW

**Comment by markelog** [comment]
@gibson042 with this change, we can include `disallowSpacesInsideParenthesizedExpression: true` and `requireSpacesInsideParentheses: {"all": true, "ignoreParenthesizedExpression": true}` for jQuery preset.

You still want to introduce such change to jQuery code style? Do you want to introduce other parentheses rules?

**Comment by gibson042** [comment]
@markelog I like the result, but not the configuration syntax. Wouldn't `allExcept: ["ParenthesizedExpression"]` be more in line with recent deprecations than introducing independent `ignore` properties?

> Do you want to introduce other parentheses rules?

I do, but haven't gotten around to it yet. However, allowing production-based exceptions like this for `requreSpacesInsideParentheses` seems to make such rules unnecessary for jQuery (but then again, _many_ JSCS rules would become redundant through expansion of `only` and `allExcept` on more general forms).

P.S. Are you planning to introduce categorization-based exceptions in `disallowSpacesInsideParentheses` here as well, to maintain parity?

**Comment by markelog** [comment]
> Wouldn't allExcept: ["ParenthesizedExpression"] be more in line with recent deprecations than introducing independent ignore properties?

The thing is, `allExcept` for this rule accepts array of token values, whereas this value wouldn't be a token. So i'm not sure which is better - polymorhic configuration value or new value.

> However, allowing production-based exceptions like this for requreSpacesInsideParentheses seems to make such rules unnecessary

Yeah, my thought exactly

> (but then again, many JSCS rules would become redundant through expansion of only and allExcept on more general forms).

I guess it depends on what is easier to support and implement some check - new additional rule value or new rule.

> P.S. Are you planning to introduce categorization-based exceptions in disallowSpacesInsideParentheses here as well, to maintain parity?

We tried the parity approach, but it generated rules or rule values that no one uses, so we would ask a contributor to do something time consuming that no one would use, that seems wrong, consistent, but wrong.

Rule values are in chaotic state at the moment, we have a lot of rules and the more rules we have the more chaotic it gets.

Hoping to straight it up in 3.0 - new config, removing unused or deprecated values/rules, etc.Yeah, hoping...

**Comment by gibson042** [comment]
Well, this rule satisfies jQuery, but it's going to start looking ugly when others need to ignore spaces inside declaration/invocation/statement parentheses. Maybe 4 cases are manageable, though.

**Comment by markelog** [comment]
Okay, lets see how it would go, will you open an issue in github.com/jquery/contribute.jquery.org?

**Pull request closed without merging**
