### PR TITLE
for issues #1899

### PR DESCRIPTION
**Pull request by cybermerlin**
#1899

### CODE REVIEW

**Comment by markelog** [comment]
Would you mind adding tests and valid example to docs?

**Comment by cybermerlin** [comment]
about test - not know

**Comment by markelog** [comment]
We can guide you through the process of writing tests if you like

**Comment by hzoo** [comment]
Check out the corresponding test file: https://github.com/jscs-dev/node-jscs/blob/master/test/specs/rules/require-padding-newlines-in-blocks.js

Basically you add more code snippets and test if it passes or fails

**Comment by markelog** [comment]
Drizzt Do'Urden is one awesome dude btw :-)

**Comment by cybermerlin** [comment]
i do it
https://github.com/jscs-dev/node-jscs/pull/1914

**Comment by markelog** [comment]
Closing in favour of https://github.com/jscs-dev/node-jscs/pull/1914

**Pull request closed without merging**
