### PR TITLE
disallowSpacesInCallExpression: report only on a node's round brace

### LINKED ISSUE #1594: Wrong disallowSpacesInCallExpression
JSCS@2.0.0

```js
const newObj = dataIsMap || dataIsSet ? new data.constructor : {};

if (dataIsMap) { // Warning

}
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25209022-wrong-disallowspacesincallexpression?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mrjoelkemp**
Fixes #1594

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Odd. I thought there were already tests for that when @markelog landed the relevant fix.

**Comment by markelog** [comment]
There was, if it wasn't coverage drop would be in orignal pr, not in yours

Anyway, this change code
```js
// Protect from the case like "new (SomeClass.extend())"(#1590)
// Protect from the case like "new (SomeClass.extend())"(#1590)
if (node.callee.type === 'CallExpression') {
    return;
}
```
is now unreachable, you can remove it

**Comment by mrjoelkemp** [comment]
Good tip. Thanks. Changes pushed.

**Comment by markelog** [comment]
LGTM

**Pull request merged**
