### PR TITLE
Changelog: use conventional-changelog and conventional-github-releaser

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by markelog** [comment]
Interesting, although i run on github requests limitation couple times, even with authentication

**Comment by stevemao** [comment]
Can you use a different token for each project?

**Comment by markelog** [comment]
> Can you use a different token for each project?

Yeah, try that, but github sometimes gives me 4998 times from 5000 tried for the last hour, or something like that, even if i just created the new user and use it crendentials.

**Comment by markelog** [comment]
Anyway, will try these changes at new release

**Comment by stevemao** [comment]
Thanks. It might take a while to make it fit in your workflow and meet your requirement but in a long run it must be beneficial.

**Comment by markelog** [comment]
Closed via c9ee4f70d99f535d1d88425b3088382983164569

**Pull request closed without merging**
