### PR TITLE
Enhancement: ignore dot folders

### LINKED ISSUE #1707: jscs looking in .git folder
Found a weird issue when running jscs on my code. It appears that `jscs .` will look in dot-directories by default (for example `.git`). The error was triggered because my branch name ends in .js and jscs therefore tried to parse `/.git/logs/refs/heads/branch.js`.

```
> jscs .

parseError: undefined at ./.git/logs/refs/heads/branch.js :
     1 |0000000000000000000000000000000000000000 897bfdbcabdfa7ce535205c6b2c751bb0d84e69e Andreas Broström <andreas.brostrom@nordnet.se> 1440067510 +0200 branch: Created from HEAD
----------------------------------------------------^
     2 |

parseError: undefined at ./.git/refs/heads/branch.js :
     1 |897bfdbcabdfa7ce535205c6b2c751bb0d84e69e
-----------^
     2 |


2 code style errors found.
```

The example can be found at: https://github.com/bstream/jscs-js-branchname/tree/branch.js

This error can be fixed by supplying ".git" to the "excludeFiles"-list in `.jscsrc`, or by supplying the specific folders and files to be tested as arguments to jscs. However, maybe jscs should ignore hidden files by default? (Which is the case with for example ESLint, see https://github.com/eslint/eslint/issues/1077)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25984132-jscs-looking-in-git-folder?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by iamstarkov**
fix #1707 tried with [testcase repo](https://github.com/bstream/jscs-js-branchname/tree/branch.js) and it works fine, all tests are green too

### CODE REVIEW

**Comment by hzoo** [comment]
I changed the docs so one these will conflict https://github.com/jscs-dev/node-jscs/pull/1697

**Comment by iamstarkov** [comment]
I will edit pr as soon as conflict will happen

**Comment by markelog** [comment]
It seems it would be a breaking change?

**Comment by iamstarkov** [comment]
prob, but I dont think that someone really store js files in dot folders, but possibility of this is not zero

**Comment by iamstarkov** [comment]
oh, i see conflicts here. will update today

**Comment by markelog** [comment]
Stil interested?

**Comment by iamstarkov** [comment]
yes, but unable to update pull-request due to broken laptop. feel free to close now, and I will update later and reopen when will have a time

**Comment by hzoo** [comment]
We can just finish it up as well

**Comment by markelog** [comment]
I would suggest stopping to search in `.git` repo, but leave the dot folders

**Comment by hzoo** [comment]
So are we just excluding `.git` then?

**Comment by markelog** [comment]
It seems as less invasive way to do it

**Comment by hzoo** [comment]
I can modify this PR and include it in 2.2.0 if we want

**Comment by hzoo** [comment]
Ok added in https://github.com/jscs-dev/node-jscs/commit/b8c1972aeef26f9a037e0f97872701dbbeaeb05a

**Pull request closed without merging**
