### PR TITLE
Misc: update dependencies

### PR DESCRIPTION
**Pull request by markelog**
Also, change update policy of the touched packages

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Carets? Why?

**Comment by markelog** [comment]
To get more rapid updates, is there any concerns?

**Comment by mrjoelkemp** [comment]
Yes, package authors shouldn't be trusted :) 

Our users shouldn't have their builds break under their feet because of one of our dependencies pushing a broken minor (even patch) update. So ideally, we'd have fixed versions. Carets create a house of cards in dependency management.

**Comment by markelog** [comment]
If we not gonna use shrinkwrap, dependency tree wouldn't be stable anyway, since fixed deps would work only if all our deps would use fixed deps.

**Comment by mrjoelkemp** [comment]
Good point.

**Comment by mikesherov** [comment]
:+1: land at will.

**Comment by zxqfox** [comment]
I've restarted appveyor, ETIMEOUT happend.

**Comment by zxqfox** [comment]
Hm:
```
.....................................................[93m.[93m.[93m. 
  [93m.[93m.......................................................
```

What's that in `appveyor` logs?

:+1: If it's fine.

**Comment by zxqfox** [comment]
> Carets? Why?

BTW. As far as I remember the last time we face carets we decided to keep tildas until 0.12 release because of support of 2 latest stable versions of node. ;-)

**Comment by mrjoelkemp** [comment]
Nice job @markelog. Thanks for contributing ;)

**Pull request closed without merging**
