### PR TITLE
Fix doc

### PR DESCRIPTION
**Pull request by Semigradsky**
Fix https://github.com/jscs-dev/jscs-dev.github.io/issues/28

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Thanks for contributing. Seems like you have a jshint error: https://travis-ci.org/jscs-dev/node-jscs/jobs/73833209

**Comment by Semigradsky** [comment]
Oh, editing from the site is bad idea. 
Fixed :v:

**Comment by mrjoelkemp** [comment]
Thanks. Seeing a build fail for io.js: https://travis-ci.org/jscs-dev/node-jscs/jobs/74187606 related to coveralls. Not entirely sure what's causing it.

**Comment by markelog** [comment]
Awesome, thanks

**Pull request closed without merging**
