### PR TITLE
validateIndentation: various bug fixes and clarity refactor

### PR DESCRIPTION
**Pull request by mikesherov**

### CODE REVIEW

**Comment by mikesherov** [comment]
@mdevils can you take a look here? I know it's a lot to review, but perhaps you can look at each commit individually.

This PR fixes a long standing issue in indentation that I've been working around for a while.

**Comment by mdevils** [comment]
Sure, I till take a look tomorrow.

**Comment by mikesherov** [comment]
@mdevils, I'm going to have @mrjoelkemp review it, as he's in my office and I can better explain to him everything that is going on in person. OK?

**Comment by mdevils** [comment]
OK, No problem.

**Pull request closed without merging**
