### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by markelog** [comment]
Why do you want to change that?

**Comment by paladox** [comment]
Well to support the latest node js release.

**Comment by markelog** [comment]
Seems like we do https://travis-ci.org/jscs-dev/node-jscs/jobs/84916786

**Comment by hzoo** [comment]
We have node 4 in travis https://github.com/jscs-dev/node-jscs/blob/master/.travis.yml - If it doesn't do anything we can remove it to cleanup package.json

**Comment by markelog** [comment]
Mostly, it is there for .8 users

**Comment by paladox** [comment]
Ok.

**Comment by markelog** [comment]
@paladox nevertheless, thank you for keeping an eye for such things!

**Pull request closed without merging**
