### PR TITLE
Docs: add JSHint and h5bp to list of users

### PR DESCRIPTION
**Pull request by hzoo**
Fixes: #1080
Closes gh-1149

### CODE REVIEW

**Comment by markelog** [comment]
Seems this list becomes pretty big, deserves its own page, or we can just "everybody uses it" :-)

**Comment by hzoo** [comment]
Haha.. maybe we have a few on the front page and another page with everyone? Or we could do logos/pictures instead to fill up the width. Also do we want to give a link to their actual .jscsrc file if it's on github?

**Comment by markelog** [comment]
> Or we could do logos/pictures instead to fill up the width

I remember that is what @mdevils wanted, preferred way for me too

> Also do we want to give a link to their actual .jscsrc file if it's on github?

It would be hard to support those links

**Comment by mdevils** [comment]
I think the best way is to have icons/logos of the most popular users on the main page and have the full list of users on a separate page. How do you think?

**Comment by markelog** [comment]
I think on the main jscs.info page it's okay, but i would try to remove it from `README.md`.

**Comment by mrjoelkemp** [comment]
Closing in favor of the suggested move of this information.

**Pull request closed without merging**
